#!/bin/sh

CP_CMD=cp
G0=/home/gandalf/research/gkyl-project/g0-branches/dir-reorg-fixes/gkylzero

# zero
mkdir -p zero
$CP_CMD $G0/zero/gkyl_gr_blackhole.h  zero/
$CP_CMD $G0/zero/gkyl_gr_minkowski.h  zero/
$CP_CMD $G0/zero/gkyl_gr_neutronstar.h  zero/
$CP_CMD $G0/zero/gkyl_gr_spacetime.h  zero/
$CP_CMD $G0/zero/gkyl_gr_spacetime.h zero/
$CP_CMD $G0/zero/gkyl_gr_spacetime_diff.h  zero/
$CP_CMD $G0/zero/gkyl_kep_scheme.h zero/
$CP_CMD $G0/zero/gkyl_mhd_src.h zero/
$CP_CMD $G0/zero/gkyl_moment_braginskii.h zero/
$CP_CMD $G0/zero/gkyl_moment_em_coupling.h zero/
$CP_CMD $G0/zero/gkyl_moment_em_coupling_priv.h zero/
$CP_CMD $G0/zero/gkyl_moment_non_ideal_priv.h zero/
$CP_CMD $G0/zero/gkyl_moment_prim_iso_euler.h zero/
$CP_CMD $G0/zero/gkyl_moment_prim_mhd.h zero/
$CP_CMD $G0/zero/gkyl_moment_prim_sr_euler.h zero/
$CP_CMD $G0/zero/gkyl_mp_scheme.h zero/
$CP_CMD $G0/zero/gkyl_sources_explicit_priv.h zero/
$CP_CMD $G0/zero/gkyl_sources_implicit_priv.h zero/
$CP_CMD $G0/zero/gkyl_ten_moment_grad_closure.h zero/
$CP_CMD $G0/zero/gkyl_wave_geom.h zero/
$CP_CMD $G0/zero/gkyl_wave_geom_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wave_prop.h  zero/
$CP_CMD $G0/zero/gkyl_wv_advect.h  zero/
$CP_CMD $G0/zero/gkyl_wv_apply_bc.h  zero/
$CP_CMD $G0/zero/gkyl_wv_burgers.h  zero/
$CP_CMD $G0/zero/gkyl_wv_canonical_pb_fluid.h  zero/
$CP_CMD $G0/zero/gkyl_wv_canonical_pb_fluid_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_coldfluid.h  zero/
$CP_CMD $G0/zero/gkyl_wv_eqn.h  zero/
$CP_CMD $G0/zero/gkyl_wv_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_euler_mixture.h  zero/
$CP_CMD $G0/zero/gkyl_wv_euler_mixture_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_medium.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_medium.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_medium_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_medium_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_iso_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_iso_euler_mixture.h  zero/
$CP_CMD $G0/zero/gkyl_wv_iso_euler_mixture_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_maxwell.h  zero/
$CP_CMD $G0/zero/gkyl_wv_maxwell_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_mhd.h  zero/
$CP_CMD $G0/zero/gkyl_wv_reactive_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_reactive_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_sr_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_ten_moment.h  zero/
$CP_CMD $G0/zero/gkyl_wv_ten_moment_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_ten_moment_priv.h zero/
$CP_CMD $G0/zero/gr_blackhole.c  zero/
$CP_CMD $G0/zero/gr_minkowski.c  zero/
$CP_CMD $G0/zero/gr_neutronstar.c  zero/
$CP_CMD $G0/zero/gr_spacetime.c  zero/
$CP_CMD $G0/zero/gr_spacetime.c zero/
$CP_CMD $G0/zero/gr_spacetime_diff.c  zero/
$CP_CMD $G0/zero/kep_scheme.c zero/
$CP_CMD $G0/zero/mhd_src.c zero/
$CP_CMD $G0/zero/moment_braginskii.c zero/
$CP_CMD $G0/zero/moment_em_coupling.c zero/
$CP_CMD $G0/zero/moment_prim_iso_euler.c zero/
$CP_CMD $G0/zero/moment_prim_mhd.c zero/
$CP_CMD $G0/zero/moment_prim_sr_euler.c zero/
$CP_CMD $G0/zero/mp_scheme.c zero/
$CP_CMD $G0/zero/sources_explicit.c zero/
$CP_CMD $G0/zero/sources_implicit.c zero/
$CP_CMD $G0/zero/ten_moment_grad_closure.c zero/
$CP_CMD $G0/zero/wave_geom.c  zero/
$CP_CMD $G0/zero/wave_geom_cu.cu  zero/
$CP_CMD $G0/zero/wave_prop.c  zero/
$CP_CMD $G0/zero/wv_advect.c  zero/
$CP_CMD $G0/zero/wv_apply_bc.c  zero/
$CP_CMD $G0/zero/wv_burgers.c  zero/
$CP_CMD $G0/zero/wv_canonical_pb_fluid.c  zero/
$CP_CMD $G0/zero/wv_coldfluid.c  zero/
$CP_CMD $G0/zero/wv_eqn.c  zero/
$CP_CMD $G0/zero/wv_euler.c  zero/
$CP_CMD $G0/zero/wv_euler_cu.cu  zero/
$CP_CMD $G0/zero/wv_euler_mixture.c  zero/
$CP_CMD $G0/zero/wv_gr_euler.c  zero/
$CP_CMD $G0/zero/wv_gr_euler.c  zero/
$CP_CMD $G0/zero/wv_gr_euler_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_euler_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_maxwell.c  zero/
$CP_CMD $G0/zero/wv_gr_maxwell.c  zero/
$CP_CMD $G0/zero/wv_gr_maxwell_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_maxwell_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_medium.c  zero/
$CP_CMD $G0/zero/wv_gr_medium.c  zero/
$CP_CMD $G0/zero/wv_gr_ultra_rel_euler.c  zero/
$CP_CMD $G0/zero/wv_gr_ultra_rel_euler.c  zero/
$CP_CMD $G0/zero/wv_gr_ultra_rel_euler_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_ultra_rel_euler_tetrad.c  zero/
$CP_CMD $G0/zero/wv_iso_euler.c  zero/
$CP_CMD $G0/zero/wv_iso_euler_mixture.c  zero/
$CP_CMD $G0/zero/wv_maxwell.c  zero/
$CP_CMD $G0/zero/wv_maxwell_cu.cu  zero/
$CP_CMD $G0/zero/wv_mhd.c  zero/
$CP_CMD $G0/zero/wv_reactive_euler.c  zero/
$CP_CMD $G0/zero/wv_sr_euler.c  zero/
$CP_CMD $G0/zero/wv_ten_moment.c  zero/
$CP_CMD $G0/zero/wv_ten_moment_cu.cu  zero/
$CP_CMD $G0/zero/wv_ten_moment_cu.cu zero/

# app
mkdir -p apps
$CP_CMD $G0/apps/gkyl_moment.h apps/
$CP_CMD $G0/apps/gkyl_moment_lw.h apps/
$CP_CMD $G0/apps/gkyl_moment_multib.h apps/
$CP_CMD $G0/apps/gkyl_moment_multib_priv.h apps/
$CP_CMD $G0/apps/gkyl_moment_priv.h apps/
$CP_CMD $G0/apps/mom_coupling.c apps/
$CP_CMD $G0/apps/mom_field.c apps/
$CP_CMD $G0/apps/mom_priv.c apps/
$CP_CMD $G0/apps/mom_species.c apps/
$CP_CMD $G0/apps/mom_update_one_step.c apps/
$CP_CMD $G0/apps/mom_update_ssp_rk.c apps/
$CP_CMD $G0/apps/moment.c apps/
$CP_CMD $G0/apps/moment_lw.c apps/
$CP_CMD $G0/apps/moment_multib.c apps/


# unit
mkdir -p unit
$CP_CMD $G0/unit/ctest_wave_geom.c unit/
$CP_CMD $G0/unit/ctest_wave_geom_helpers.c unit/
$CP_CMD $G0/unit/ctest_wv_apply_bc.c unit/
$CP_CMD $G0/unit/ctest_wv_euler.c unit/
$CP_CMD $G0/unit/ctest_wv_euler_mixture.c unit/
$CP_CMD $G0/unit/ctest_wv_gr_euler.c unit/
$CP_CMD $G0/unit/ctest_wv_gr_euler_tetrad.c unit/
$CP_CMD $G0/unit/ctest_wv_gr_maxwell.c unit/
$CP_CMD $G0/unit/ctest_wv_gr_maxwell_tetrad.c unit/
$CP_CMD $G0/unit/ctest_wv_gr_medium.c unit/
$CP_CMD $G0/unit/ctest_wv_gr_ultra_rel_euler.c unit/
$CP_CMD $G0/unit/ctest_wv_gr_ultra_rel_euler_tetrad.c unit/
$CP_CMD $G0/unit/ctest_wv_iso_euler.c unit/
$CP_CMD $G0/unit/ctest_wv_iso_euler_mixture.c unit/
$CP_CMD $G0/unit/ctest_wv_maxwell.c unit/
$CP_CMD $G0/unit/ctest_wv_mhd.c unit/
$CP_CMD $G0/unit/ctest_wv_reactive_euler.c unit/
$CP_CMD $G0/unit/ctest_wv_sr_euler.c unit/
$CP_CMD $G0/unit/ctest_wv_ten_moment.c unit/

# C regression tests
mkdir -p creg
$CP_CMD $G0/regression/rt_10m_burch.c creg/
$CP_CMD $G0/regression/rt_10m_burch_grad_closure.c creg/
$CP_CMD $G0/regression/rt_10m_expanding.c creg/
$CP_CMD $G0/regression/rt_10m_expanding_axi_sodshock.c creg/
$CP_CMD $G0/regression/rt_10m_expanding_sodshock.c creg/
$CP_CMD $G0/regression/rt_10m_gem.c creg/
$CP_CMD $G0/regression/rt_10m_gem_grad_closure.c creg/
$CP_CMD $G0/regression/rt_10m_lhdi.c creg/
$CP_CMD $G0/regression/rt_10m_lhdi_grad_closure.c creg/
$CP_CMD $G0/regression/rt_10m_par_firehose.c creg/
$CP_CMD $G0/regression/rt_10m_par_firehose_grad_closure.c creg/
$CP_CMD $G0/regression/rt_10m_riem.c creg/
$CP_CMD $G0/regression/rt_10m_riem_grad_closure.c creg/
$CP_CMD $G0/regression/rt_10m_sodshock.c creg/
$CP_CMD $G0/regression/rt_10m_sodshock_lax.c creg/
$CP_CMD $G0/regression/rt_5m_burch.c creg/
$CP_CMD $G0/regression/rt_5m_elc_heat_flux.c creg/
$CP_CMD $G0/regression/rt_5m_em_advect.c creg/
$CP_CMD $G0/regression/rt_5m_em_advect_resonant.c creg/
$CP_CMD $G0/regression/rt_5m_expanding.c creg/
$CP_CMD $G0/regression/rt_5m_expanding_axi_sodshock.c creg/
$CP_CMD $G0/regression/rt_5m_expanding_sodshock.c creg/
$CP_CMD $G0/regression/rt_5m_friction.c creg/
$CP_CMD $G0/regression/rt_5m_gem.c creg/
$CP_CMD $G0/regression/rt_5m_hartmann.c creg/
$CP_CMD $G0/regression/rt_5m_ion_heat_flux.c creg/
$CP_CMD $G0/regression/rt_5m_mom_beach.c creg/
$CP_CMD $G0/regression/rt_5m_riem.c creg/
$CP_CMD $G0/regression/rt_5m_rt.c creg/
$CP_CMD $G0/regression/rt_advect_wv.c creg/
$CP_CMD $G0/regression/rt_advect_wv_mp.c creg/
$CP_CMD $G0/regression/rt_arg_parse.h creg/
$CP_CMD $G0/regression/rt_burgers_shock.c creg/
$CP_CMD $G0/regression/rt_burgers_shock_mp.c creg/
$CP_CMD $G0/regression/rt_coldfluid_beach.c creg/
$CP_CMD $G0/regression/rt_coldfluid_clouda.c creg/
$CP_CMD $G0/regression/rt_coldfluid_em_coupling.c creg/
$CP_CMD $G0/regression/rt_euler_axi_sodshock.c creg/
$CP_CMD $G0/regression/rt_euler_axi_vac_riem.c creg/
$CP_CMD $G0/regression/rt_euler_bump_in_channel.c creg/
$CP_CMD $G0/regression/rt_euler_c2p_sodshock.c creg/
$CP_CMD $G0/regression/rt_euler_cart_axi_sodshock.c creg/
$CP_CMD $G0/regression/rt_euler_kh_2d.c creg/
$CP_CMD $G0/regression/rt_euler_mixture_fedkiw_shock.c creg/
$CP_CMD $G0/regression/rt_euler_mixture_shock_bubble.c creg/
$CP_CMD $G0/regression/rt_euler_noh_1d.c creg/
$CP_CMD $G0/regression/rt_euler_p_perturbation.c creg/
$CP_CMD $G0/regression/rt_euler_reflect_2d.c creg/
$CP_CMD $G0/regression/rt_euler_riem_2d_hll.c creg/
$CP_CMD $G0/regression/rt_euler_riem_2d_hllc.c creg/
$CP_CMD $G0/regression/rt_euler_riem_2d_lax.c creg/
$CP_CMD $G0/regression/rt_euler_riem_2d_roe.c creg/
$CP_CMD $G0/regression/rt_euler_riem_3d.c creg/
$CP_CMD $G0/regression/rt_euler_rt.c creg/
$CP_CMD $G0/regression/rt_euler_sodshock.c creg/
$CP_CMD $G0/regression/rt_euler_sodshock_lax.c creg/
$CP_CMD $G0/regression/rt_euler_sodshock_mp.c creg/
$CP_CMD $G0/regression/rt_euler_superwedge.c creg/
$CP_CMD $G0/regression/rt_euler_vac.c creg/
$CP_CMD $G0/regression/rt_euler_vac_riem_1d.c creg/
$CP_CMD $G0/regression/rt_euler_wave_2d_kep.c creg/
$CP_CMD $G0/regression/rt_euler_wave_2d_mp.c creg/
$CP_CMD $G0/regression/rt_euler_wave_2d_wv.c creg/
$CP_CMD $G0/regression/rt_euler_wedge_sodshock.c creg/
$CP_CMD $G0/regression/rt_gr_bhl_spinning.c creg/
$CP_CMD $G0/regression/rt_gr_bhl_spinning_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_bhl_static.c creg/
$CP_CMD $G0/regression/rt_gr_bhl_static_neutronstar.c creg/
$CP_CMD $G0/regression/rt_gr_bhl_static_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_blackhole_spinning.c creg/
$CP_CMD $G0/regression/rt_gr_blackhole_static.c creg/
$CP_CMD $G0/regression/rt_gr_bz_monopole_fast.c creg/
$CP_CMD $G0/regression/rt_gr_bz_monopole_fast_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_bz_monopole_slow.c creg/
$CP_CMD $G0/regression/rt_gr_bz_monopole_slow_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_current_sheet.c creg/
$CP_CMD $G0/regression/rt_gr_current_sheet_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_einstein_plane_shock.c creg/
$CP_CMD $G0/regression/rt_gr_kh_2d.c creg/
$CP_CMD $G0/regression/rt_gr_mild_shock.c creg/
$CP_CMD $G0/regression/rt_gr_mild_shock_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_perturbed_density.c creg/
$CP_CMD $G0/regression/rt_gr_quadrants_2d.c creg/
$CP_CMD $G0/regression/rt_gr_strong_blast.c creg/
$CP_CMD $G0/regression/rt_gr_ultra_rel_bhl_spinning.c creg/
$CP_CMD $G0/regression/rt_gr_ultra_rel_bhl_spinning_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_ultra_rel_bhl_static.c creg/
$CP_CMD $G0/regression/rt_gr_ultra_rel_bhl_static_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_ultra_rel_shock.c creg/
$CP_CMD $G0/regression/rt_gr_ultra_rel_shock_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_wald_magnetosphere_spinning.c creg/
$CP_CMD $G0/regression/rt_gr_wald_magnetosphere_spinning_tetrad.c creg/
$CP_CMD $G0/regression/rt_gr_wald_magnetosphere_static.c creg/
$CP_CMD $G0/regression/rt_gr_wald_magnetosphere_static_neutronstar.c creg/
$CP_CMD $G0/regression/rt_gr_wald_magnetosphere_static_tetrad.c creg/
$CP_CMD $G0/regression/rt_iso_euler_friction.c creg/
$CP_CMD $G0/regression/rt_iso_euler_hartmann.c creg/
$CP_CMD $G0/regression/rt_iso_euler_mixture_fedkiw_shock.c creg/
$CP_CMD $G0/regression/rt_iso_euler_mixture_shock_bubble.c creg/
$CP_CMD $G0/regression/rt_iso_euler_sodshock.c creg/
$CP_CMD $G0/regression/rt_iso_euler_sodshock_lax.c creg/
$CP_CMD $G0/regression/rt_iso_gem.c creg/
$CP_CMD $G0/regression/rt_maxwell_annular_wg.c creg/
$CP_CMD $G0/regression/rt_maxwell_annulus.c creg/
$CP_CMD $G0/regression/rt_maxwell_axi_wg.c creg/
$CP_CMD $G0/regression/rt_maxwell_expanding.c creg/
$CP_CMD $G0/regression/rt_maxwell_expanding_2d.c creg/
$CP_CMD $G0/regression/rt_maxwell_plane_wave_1d.c creg/
$CP_CMD $G0/regression/rt_maxwell_plane_wave_1d_mp.c creg/
$CP_CMD $G0/regression/rt_maxwell_plane_wave_2d.c creg/
$CP_CMD $G0/regression/rt_maxwell_plane_wave_2d_mp.c creg/
$CP_CMD $G0/regression/rt_maxwell_reflect_2d.c creg/
$CP_CMD $G0/regression/rt_maxwell_wg_2d.c creg/
$CP_CMD $G0/regression/rt_mhd_brio_wu.c creg/
$CP_CMD $G0/regression/rt_mhd_ot.c creg/
$CP_CMD $G0/regression/rt_mhd_rj2.c creg/
$CP_CMD $G0/regression/rt_reactive_euler_detonation.c creg/
$CP_CMD $G0/regression/rt_sr_euler_KH_2d.c creg/
$CP_CMD $G0/regression/rt_sr_euler_riem_2d.c creg/
$CP_CMD $G0/regression/rt_sr_euler_sodshock.c creg/

# Lua regression tests
mkdir -p luareg
