#!/bin/sh

CP_CMD=cp
G0=/home/gandalf/research/gkyl-project/g0-branches/dir-reorg-fixes/gkylzero

# zero
mkdir -p zero
$CP_CMD $G0/zero/gkyl_gr_blackhole.h  zero/
$CP_CMD $G0/zero/gkyl_gr_minkowski.h  zero/
$CP_CMD $G0/zero/gkyl_gr_neutronstar.h  zero/
$CP_CMD $G0/zero/gkyl_gr_spacetime.h  zero/
$CP_CMD $G0/zero/gkyl_gr_spacetime.h zero/
$CP_CMD $G0/zero/gkyl_gr_spacetime_diff.h  zero/
$CP_CMD $G0/zero/gkyl_kep_scheme.h zero/
$CP_CMD $G0/zero/gkyl_mhd_src.h zero/
$CP_CMD $G0/zero/gkyl_moment_braginskii.h zero/
$CP_CMD $G0/zero/gkyl_moment_em_coupling.h zero/
$CP_CMD $G0/zero/gkyl_moment_em_coupling_priv.h zero/
$CP_CMD $G0/zero/gkyl_moment_non_ideal_priv.h zero/
$CP_CMD $G0/zero/gkyl_moment_prim_iso_euler.h zero/
$CP_CMD $G0/zero/gkyl_moment_prim_mhd.h zero/
$CP_CMD $G0/zero/gkyl_moment_prim_sr_euler.h zero/
$CP_CMD $G0/zero/gkyl_mp_scheme.h zero/
$CP_CMD $G0/zero/gkyl_sources_explicit_priv.h zero/
$CP_CMD $G0/zero/gkyl_sources_implicit_priv.h zero/
$CP_CMD $G0/zero/gkyl_ten_moment_grad_closure.h zero/
$CP_CMD $G0/zero/gkyl_wave_geom.h zero/
$CP_CMD $G0/zero/gkyl_wave_geom_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wave_prop.h  zero/
$CP_CMD $G0/zero/gkyl_wv_advect.h  zero/
$CP_CMD $G0/zero/gkyl_wv_apply_bc.h  zero/
$CP_CMD $G0/zero/gkyl_wv_burgers.h  zero/
$CP_CMD $G0/zero/gkyl_wv_canonical_pb_fluid.h  zero/
$CP_CMD $G0/zero/gkyl_wv_canonical_pb_fluid_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_coldfluid.h  zero/
$CP_CMD $G0/zero/gkyl_wv_eqn.h  zero/
$CP_CMD $G0/zero/gkyl_wv_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_euler_mixture.h  zero/
$CP_CMD $G0/zero/gkyl_wv_euler_mixture_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_euler_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_maxwell_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_medium.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_medium.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_medium_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_medium_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_tetrad.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_gr_ultra_rel_euler_tetrad_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_iso_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_iso_euler_mixture.h  zero/
$CP_CMD $G0/zero/gkyl_wv_iso_euler_mixture_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_maxwell.h  zero/
$CP_CMD $G0/zero/gkyl_wv_maxwell_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_mhd.h  zero/
$CP_CMD $G0/zero/gkyl_wv_reactive_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_reactive_euler_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_sr_euler.h  zero/
$CP_CMD $G0/zero/gkyl_wv_ten_moment.h  zero/
$CP_CMD $G0/zero/gkyl_wv_ten_moment_priv.h  zero/
$CP_CMD $G0/zero/gkyl_wv_ten_moment_priv.h zero/
$CP_CMD $G0/zero/gr_blackhole.c  zero/
$CP_CMD $G0/zero/gr_minkowski.c  zero/
$CP_CMD $G0/zero/gr_neutronstar.c  zero/
$CP_CMD $G0/zero/gr_spacetime.c  zero/
$CP_CMD $G0/zero/gr_spacetime.c zero/
$CP_CMD $G0/zero/gr_spacetime_diff.c  zero/
$CP_CMD $G0/zero/kep_scheme.c zero/
$CP_CMD $G0/zero/mhd_src.c zero/
$CP_CMD $G0/zero/moment_braginskii.c zero/
$CP_CMD $G0/zero/moment_em_coupling.c zero/
$CP_CMD $G0/zero/moment_prim_iso_euler.c zero/
$CP_CMD $G0/zero/moment_prim_mhd.c zero/
$CP_CMD $G0/zero/moment_prim_sr_euler.c zero/
$CP_CMD $G0/zero/mp_scheme.c zero/
$CP_CMD $G0/zero/sources_explicit.c zero/
$CP_CMD $G0/zero/sources_implicit.c zero/
$CP_CMD $G0/zero/ten_moment_grad_closure.c zero/
$CP_CMD $G0/zero/wave_geom.c  zero/
$CP_CMD $G0/zero/wave_geom_cu.cu  zero/
$CP_CMD $G0/zero/wave_prop.c  zero/
$CP_CMD $G0/zero/wv_advect.c  zero/
$CP_CMD $G0/zero/wv_apply_bc.c  zero/
$CP_CMD $G0/zero/wv_burgers.c  zero/
$CP_CMD $G0/zero/wv_canonical_pb_fluid.c  zero/
$CP_CMD $G0/zero/wv_coldfluid.c  zero/
$CP_CMD $G0/zero/wv_eqn.c  zero/
$CP_CMD $G0/zero/wv_euler.c  zero/
$CP_CMD $G0/zero/wv_euler_cu.cu  zero/
$CP_CMD $G0/zero/wv_euler_mixture.c  zero/
$CP_CMD $G0/zero/wv_gr_euler.c  zero/
$CP_CMD $G0/zero/wv_gr_euler.c  zero/
$CP_CMD $G0/zero/wv_gr_euler_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_euler_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_maxwell.c  zero/
$CP_CMD $G0/zero/wv_gr_maxwell.c  zero/
$CP_CMD $G0/zero/wv_gr_maxwell_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_maxwell_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_medium.c  zero/
$CP_CMD $G0/zero/wv_gr_medium.c  zero/
$CP_CMD $G0/zero/wv_gr_ultra_rel_euler.c  zero/
$CP_CMD $G0/zero/wv_gr_ultra_rel_euler.c  zero/
$CP_CMD $G0/zero/wv_gr_ultra_rel_euler_tetrad.c  zero/
$CP_CMD $G0/zero/wv_gr_ultra_rel_euler_tetrad.c  zero/
$CP_CMD $G0/zero/wv_iso_euler.c  zero/
$CP_CMD $G0/zero/wv_iso_euler_mixture.c  zero/
$CP_CMD $G0/zero/wv_maxwell.c  zero/
$CP_CMD $G0/zero/wv_maxwell_cu.cu  zero/
$CP_CMD $G0/zero/wv_mhd.c  zero/
$CP_CMD $G0/zero/wv_reactive_euler.c  zero/
$CP_CMD $G0/zero/wv_sr_euler.c  zero/
$CP_CMD $G0/zero/wv_ten_moment.c  zero/
$CP_CMD $G0/zero/wv_ten_moment_cu.cu  zero/
$CP_CMD $G0/zero/wv_ten_moment_cu.cu zero/

# app
mkdir -p apps
$CP_CMD $G0/apps/gkyl_moment.h apps/
$CP_CMD $G0/apps/gkyl_moment_lw.h apps/
$CP_CMD $G0/apps/gkyl_moment_multib.h apps/
$CP_CMD $G0/apps/gkyl_moment_multib_priv.h apps/
$CP_CMD $G0/apps/gkyl_moment_priv.h apps/
$CP_CMD $G0/apps/mom_coupling.c apps/
$CP_CMD $G0/apps/mom_field.c apps/
$CP_CMD $G0/apps/mom_priv.c apps/
$CP_CMD $G0/apps/mom_species.c apps/
$CP_CMD $G0/apps/mom_update_one_step.c apps/
$CP_CMD $G0/apps/mom_update_ssp_rk.c apps/
$CP_CMD $G0/apps/moment.c apps/
$CP_CMD $G0/apps/moment_lw.c apps/
$CP_CMD $G0/apps/moment_multib.c apps/


# unit
mkdir -p unit

# regression
mkdir -p unit
